### ISSUE TITLE
What have you changed?

### ISSUE THREAD

**Issue by samrocketman** [gabrielrcouto/reaver-wps#1]
This would be useful for studying if you added the original changes on the first commit and then add the mac changer on the second.  Then there would be a diff.

**Comment by gabrielrcouto** [comment]
Thank you @samrocketman, I commited on a new branch the original code, and you can see the diff (on the opossite direction, but basically is the same thing). Just click above on my commit.

**Comment by samrocketman** [comment]
Thanks :)

**Comment by K0K0SHA** [comment]
I was going to create a diff too. Thank you.
