### ISSUE TITLE
can it be cross compiled?

### ISSUE THREAD

**Issue by de3pkeeper** [gabrielrcouto/reaver-wps#4]
hello,
script kiddie here.

can I cross compile this using the LEDE SDK for ramips mt7621 targets?
the sdk uses a list of "feeds" that point to the desired git repo and loads the sources.
Then it wants to build some sort of .index file from the feed which it does without errors.

so the feed is loaded ok form here but when issuing ./feeds install reaver-wps it ends up not finding the thing and the corresponding .index file for reaver-wps is actually empty...

am I missing something that those index files are built from?

thanks

**Comment by gabrielrcouto** [comment]
Hello @de3pkeeper,

Sorry, I don't found any documentation to help you. I suggest you to contact the LEDE SDK team for helping with this.

Good luck,
Gabriel
